//ALERTS
export const ADD_ALERT = "ADD_ALERT";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

//AUTH
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const REQUEST_USER = "REQUEST_USER";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const START_LOGOUT = "START_LOGOUT";
export const LOGOUT = "LOGOUT";

//Profile
export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const PROFILE_LOADED = "PROFILE_LOADED";
export const PROFILES_LOADED = "PROFILES_LOADED";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const ADD_EXP_PROFILE = "ADD_EXP_PROFILE";
export const ADD_EDU_PROFILE = "ADD_EDU_PROFILE";
export const DELETE_EXPERIENCE = "DELETE_EXPERIENCE";
export const DELETE_EDUCATION = "DELETE_EDUCATION";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const GITHUB_REQUEST = "GITHUB_REQUEST";
export const GITHUB_LOADED = "GITHUB_LOADED";
